"""create courses and course registrations

Revision ID: 00f7fc38ba77
Revises: 85d87d97c121
Create Date: 2026-08-09 23:57:12.983166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f7fc38ba77'
down_revision: Union[str, Sequence[str], None] = '85d87d97c121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_courses_code')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index('uq_courses_lower_name', 'courses', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('class_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_name', sa.String(length=150), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'course_id', name='uq_class_courses_classroom_course')
    )
    op.create_index(op.f('ix_class_courses_classroom_id'), 'class_courses', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_class_courses_course_id'), 'class_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_class_courses_created_by_user_id'), 'class_courses', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_class_courses_id'), 'class_courses', ['id'], unique=False)
    op.create_table('course_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('class_course_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_course_id'], ['class_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['class_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'class_course_id', name='uq_course_registrations_membership_class_course')
    )
    op.create_index(op.f('ix_course_registrations_class_course_id'), 'course_registrations', ['class_course_id'], unique=False)
    op.create_index(op.f('ix_course_registrations_id'), 'course_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_course_registrations_membership_id'), 'course_registrations', ['membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_registrations_membership_id'), table_name='course_registrations')
    op.drop_index(op.f('ix_course_registrations_id'), table_name='course_registrations')
    op.drop_index(op.f('ix_course_registrations_class_course_id'), table_name='course_registrations')
    op.drop_table('course_registrations')
    op.drop_index(op.f('ix_class_courses_id'), table_name='class_courses')
    op.drop_index(op.f('ix_class_courses_created_by_user_id'), table_name='class_courses')
    op.drop_index(op.f('ix_class_courses_course_id'), table_name='class_courses')
    op.drop_index(op.f('ix_class_courses_classroom_id'), table_name='class_courses')
    op.drop_table('class_courses')
    op.drop_index('uq_courses_lower_name', table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
