"""add rag resources and chunks

Revision ID: 725bcd6fad8e
Revises: f168abb59f13
Create Date: 2026-08-27 06:52:07.052265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '725bcd6fad8e'
down_revision: Union[str, Sequence[str], None] = 'f168abb59f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('class_course_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_course_id'], ['class_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_class_course_id'), 'rag_chunks', ['class_course_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_classroom_id'), 'rag_chunks', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_id'), 'rag_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_source_id'), 'rag_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_source_type'), 'rag_chunks', ['source_type'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('class_course_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_course_id'], ['class_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_class_course_id'), 'resources', ['class_course_id'], unique=False)
    op.create_index(op.f('ix_resources_classroom_id'), 'resources', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_classroom_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_class_course_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_rag_chunks_source_type'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_source_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_classroom_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_class_course_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    # ### end Alembic commands ###
