import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import { joinClassroom } from "../api/classrooms.js";
import Alert from "../components/Alert.jsx";
import FormField from "../components/FormField.jsx";
import { parseApiError } from "../utils/errors.js";

const initialForm = {
  class_id: "",
  join_code: "",
};

function JoinClassPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState(initialForm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState("");

  function handleChange(event) {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setIsSubmitting(true);
    setError(null);
    setSuccess("");

    try {
      const membership = await joinClassroom(
        Number(form.class_id),
        form.join_code.trim().toUpperCase(),
      );
      setSuccess("Membership request submitted. Waiting for representative approval.");
      window.setTimeout(() => {
        navigate(`/classes/${membership.classroom_id}`, { replace: true });
      }, 500);
    } catch (apiError) {
      setError(parseApiError(apiError));
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <section className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
      <div className="space-y-4">
        <p className="text-sm font-semibold uppercase tracking-wide text-[#256f68]">
          Join class
        </p>
        <h1 className="text-3xl font-bold text-[#172033] sm:text-4xl">
          Request Membership
        </h1>
        <p className="max-w-xl text-base leading-7 text-[#566176]">
          Use the class ID and join code shared by your class representative.
          Requests remain pending until a representative approves them.
        </p>
      </div>

      <form
        className="rounded-md border border-[#dde4ef] bg-white p-5 shadow-sm sm:p-6"
        onSubmit={handleSubmit}
      >
        <div className="space-y-5">
          {error ? (
            <Alert
              title="Could not request membership"
              message={error.message}
              items={error.items}
            />
          ) : null}
          {success ? (
            <Alert type="success" title="Request submitted" message={success} />
          ) : null}

          <FormField
            id="join-class-id"
            inputMode="numeric"
            label="Class ID"
            min="1"
            name="class_id"
            onChange={handleChange}
            required
            type="number"
            value={form.class_id}
          />
          <FormField
            autoComplete="off"
            helpText="Join codes are generated by the backend when a representative creates a class."
            id="join-code"
            label="Join code"
            name="join_code"
            onChange={handleChange}
            placeholder="ABC12345"
            required
            value={form.join_code}
          />

          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <Link
              to="/classes"
              className="text-sm font-semibold text-[#256f68] hover:text-[#1f5d58]"
            >
              Back to classes
            </Link>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center justify-center rounded-md bg-[#256f68] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#1f5d58] focus:outline-none focus:ring-2 focus:ring-[#256f68] focus:ring-offset-2 disabled:cursor-not-allowed disabled:bg-[#8ebbb5]"
            >
              {isSubmitting ? "Submitting request..." : "Request membership"}
            </button>
          </div>
        </div>
      </form>
    </section>
  );
}

export default JoinClassPage;
