import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

import { joinClassroom } from "../api/classrooms.js";
import Alert from "../components/Alert.jsx";
import Button from "../components/Button.jsx";
import FormField from "../components/FormField.jsx";
import PageHeader from "../components/PageHeader.jsx";
import { parseApiError } from "../utils/errors.js";

const initialForm = {
  class_id: "",
  join_code: "",
};

function JoinClassPage() {
  const navigate = useNavigate();
  const [form, setForm] = useState(initialForm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState("");

  function handleChange(event) {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setIsSubmitting(true);
    setError(null);
    setSuccess("");

    try {
      const membership = await joinClassroom(
        Number(form.class_id),
        form.join_code.trim().toUpperCase(),
      );
      setSuccess("Membership request submitted. Waiting for representative approval.");
      window.setTimeout(() => {
        navigate(`/classes/${membership.classroom_id}`, { replace: true });
      }, 500);
    } catch (apiError) {
      setError(parseApiError(apiError));
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <section className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
      <PageHeader
        description="Use the class ID and join code shared by your class representative. Requests remain pending until a representative approves them."
        eyebrow="Join class"
        title="Request Membership"
      />

      <form
        className="cf-card p-5 sm:p-6"
        onSubmit={handleSubmit}
      >
        <div className="space-y-5">
          {error ? (
            <Alert
              title="Could not request membership"
              message={error.message}
              items={error.items}
            />
          ) : null}
          {success ? (
            <Alert type="success" title="Request submitted" message={success} />
          ) : null}

          <FormField
            id="join-class-id"
            inputMode="numeric"
            label="Class ID"
            min="1"
            name="class_id"
            onChange={handleChange}
            required
            type="number"
            value={form.class_id}
          />
          <FormField
            autoComplete="off"
            helpText="Join codes are generated by the backend when a representative creates a class."
            id="join-code"
            label="Join code"
            name="join_code"
            onChange={handleChange}
            placeholder="ABC12345"
            required
            value={form.join_code}
          />

          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <Link
              to="/classes"
              className="text-sm font-semibold text-blue-700 hover:text-blue-900 cf-focus"
            >
              Back to classes
            </Link>
            <Button disabled={isSubmitting} type="submit" variant="primary">
              {isSubmitting ? "Submitting request..." : "Request membership"}
            </Button>
          </div>
        </div>
      </form>
    </section>
  );
}

export default JoinClassPage;
